# Experiment
description: bert-base-uncased on the Certainty task only
logdir: /mnt/iusers01/nactem01/u14498jv/scratch/n2c2_track1/context/bert_baseline_logs/
name: bert/certainty
random_seed: 0

# Data
data_dir: /mnt/iusers01/nactem01/u14498jv/Projects/n2c2-track1/n2c2Track1TrainingData-v3/data_v3/
max_train_examples: null
sentences_dir: /mnt/iusers01/nactem01/u14498jv/Projects/n2c2-track1/n2c2Track1TrainingData-v3/segmented
tasks_to_load:
- Certainty
window_size: 0

# Model
bert_model_name_or_path: bert-base-uncased
dropout_prob: 0.1
entity_pool_fn: max
freeze_pretrained: false
mark_entities: false
max_seq_length: 300
model_name: bert-sequence-classifier
use_entity_spans: false

# Training
batch_size: 32
class_weights: none
gradient_clip_val: 10.0
lr: 3.0e-05
max_epochs: 10
sample_strategy: none
weight_decay: 0.0

