# Experiment
name: clinical_bert/mtl/action_negation/version_3/cv_split_runs/0
description: Bio_ClinicalBERT using entity spans on the Action and Negation tasks
  with label smoothing
logdir: /mnt/iusers01/nactem01/u14498jv/scratch/n2c2_track1/context/bert_baseline_logs/
random_seed: 0

# Data
data_dir: /mnt/iusers01/nactem01/u14498jv/Projects/n2c2-track1/n2c2Track1TrainingData-v3/cv_splits/0/
sentences_dir: /mnt/iusers01/nactem01/u14498jv/Projects/n2c2-track1/n2c2Track1TrainingData-v3/cv_splits/0/segmented
tasks_to_load:
- Action
- Negation
window_size: 1
max_train_examples: null
auxiliary_data: {}
dataset_sample_strategy: proportional

# Model
model_name: bert-sequence-classifier
bert_model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
freeze_pretrained: false
use_entity_spans: true
entity_pool_fn: first-last
mark_entities: true
max_seq_length: 300
dropout_prob: 0.2

# Losses
classifier_loss_fn: cross-entropy
classifier_loss_kwargs:
  label_smoothing: 0.1
mask_loss_fn: ratio
mask_loss_kwargs: {}

# Training
batch_size: 32
sample_strategy: null
lr: 3.0e-05
weight_decay: 0.0
gradient_clip_val: 10.0
max_epochs: 10

