# Experiment
name: clinical_bert/action_entity_marked
description: Bio_ClinicalBERT using entity spans on the Action task only, levitated markers on AUX, VERB
logdir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/context/bert_baselines/logs/
random_seed: 0

# Data
dataset_name: n2c2Context
data_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v3/data_v3/
sentences_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v3/segmented/
tasks_to_load:
- Action
window_size: 1
max_train_examples: null
auxiliary_data: {}
dataset_sample_strategy: sequential
dataset_sampler_kwargs: {}

# Model
model_name: bert-sequence-classifier
bert_model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
freeze_pretrained: false
use_entity_spans: true
entity_pool_fn: first-last
mark_entities: false
entity_markers: ["[unused0]", "[unused1]"]
use_levitated_markers: true
levitated_marker_pool_fn: max
levitated_pos_tags: ["VERB"]
max_seq_length: 300
dropout_prob: 0.3

# Losses
classifier_loss_fn: cross-entropy
classifier_loss_kwargs: {}
mask_loss_fn: ratio
mask_loss_kwargs: {}

# Training
batch_size: 8
sample_strategy: null
lr: 3.0e-05
weight_decay: 0.0
gradient_clip_val: 0.5
max_epochs: 10

