batch_size: 1
data_dir: ''
description: ''
freeze_pretrained: false
gradient_clip_val: 10.0
lr: 0.001
max_epochs: 1
max_seq_length: 128
max_train_examples: null
model_name_or_path: ''
name: default_experiment
random_seed: 0
sentences_dir: ''
tasks_to_load: all
use_entity_spans: false
weight_decay: 0.0
window_size: 0
