# Experiment
description: test experiment with v2 data release
logdir: logs/
name: test
random_seed: 0

# Data
data_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v2/data_v2
max_train_examples: 10
sentences_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v2/segmented
tasks_to_load:
- Certainty
window_size: 0

# Model
bert_model_name_or_path: bert-base-uncased
dropout_prob: 0.2
entity_pool_fn: max
freeze_pretrained: false
mark_entities: false
max_seq_length: 256
model_name: bert-sequence-classifier
use_entity_spans: false

# Training
batch_size: 2
class_weights: balanced
gradient_clip_val: 10.0
lr: 0.001
max_epochs: 2
sample_strategy: none
weight_decay: 0.0

