# Experiment
name: "test_entity_spans"
description: "test experiment using entity span max pooling"
random_seed: 0

# Data
data_dir: '/home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData/data'
sentences_dir: '/home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData/segmented'
#tasks_to_load: all
tasks_to_load: ["Negation", "Certainity"]
window_size: 0
max_train_examples: 50

# Model
model_name: "bert-sequence-classifier"
bert_model_name_or_path: 'bert-base-uncased'
freeze_pretrained: false
use_entity_spans: true
max_seq_length: 128

# Training
batch_size: 10
lr: 0.001
weight_decay: 0.0
gradient_clip_val: 10.0
max_epochs: 2
