# Experiment
description: test experiment with v2 data release using entity span embeddings
logdir: logs/
name: test_entity_spans_v2
random_seed: 0

# Data
data_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v2/data_v2
max_train_examples: 50
sentences_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v2/segmented
tasks_to_load: all
window_size: 0

# Model
bert_model_name_or_path: bert-base-uncased
entity_pool_fn: mean
freeze_pretrained: false
max_seq_length: 256
model_name: bert-sequence-classifier
use_entity_spans: true

# Training
batch_size: 2
gradient_clip_val: 10.0
lr: 0.001
max_epochs: 2
sample_strategy: none
weight_decay: 0.0

