# Experiment
name: test
description: test
logdir: logs/
random_seed: 0

# Data
dataset_name: n2c2Context
data_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v3/data_v3
sentences_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v3/segmented
tasks_to_load:
- Certainty
window_size: 0
max_train_examples: 100
auxiliary_data: {}
dataset_sample_strategy: sequential
dataset_sampler_kwargs: {}

# Model
model_name: bert-sequence-classifier
bert_model_name_or_path: bert-base-uncased
freeze_pretrained: false
use_entity_spans: true
entity_pool_fn: first-last
mark_entities: true
entity_markers: ["[unused0]", "[unused1]"]
use_levitated_markers: true
levitated_marker_pool_fn: first-last
max_seq_length: 256
dropout_prob: 0.2

# Losses
classifier_loss_fn: cross-entropy
classifier_loss_kwargs: {}
mask_loss_fn: ratio
mask_loss_kwargs: {}

# Training
batch_size: 10
sample_strategy: null
lr: 0.001
weight_decay: 0.0
gradient_clip_val: 10.0
max_epochs: 2

