# Experiment
description: test experiment with bio+clinical BERT
logdir: logs/
name: test_clinical_bert
random_seed: 0

# Data
data_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v2/data_v2
max_train_examples: 50
sentences_dir: /home/u14498jv/Documents/Projects/n2c2-track1/n2c2Track1TrainingData-v2/segmented
tasks_to_load:
- Negation
- Certainty
window_size: 0

# Model
bert_model_name_or_path: emilyalsentzer/Bio_ClinicalBERT
dropout_prob: 0.1
entity_pool_fn: max
freeze_pretrained: false
mark_entities: false
max_seq_length: 256
model_name: bert-sequence-classifier
use_entity_spans: false

# Losses
classifier_loss_fn: cross-entropy
classifier_loss_kwargs: {}
mask_loss_fn: ratio
mask_loss_kwargs: {}

# Training
batch_size: 10
gradient_clip_val: 10.0
lr: 0.001
max_epochs: 2
sample_strategy: null
weight_decay: 0.0

