device: 0
seed: 2021
log_interval: 300

# DATA params
data_dir: ../data/
#pred_dir: ../results/predictions/
dev_miss: ../dev_miss.txt
results_folder: ../results/
logs: ../logs/
## Log params
#exp_name: 'n2c2'
model_name: 'bert'
# Hyper-parameters
batch_size: 32
epochs: 10
warmup_epochs: 0
## Markers params
max_tok_len: 300
#max_verbs : 10 set in io.py
ent_tok0: '[unused0]'
ent_tok1: '[unused1]'

## Bert params
dummy_data: False
hidden_dim: 768 
#intermediate_dim: 2304 #3*768
# max_sent_len: 50
enc_dim: 768
enc_layers: 12
dropout: 0.3
lr: 0.00004
weight_decay: 0.001
clip: 10
## Train params
patience: 5
accumulate_batches: 1
threshold: 0.5
event_weight: 0.5
# FLAGS
early_stop: True
pipeline: False
# include_positions: True
# sort_verbs: False     always False
# pool_fn: 'max'        set in io.poy
# single_marker: True   set in io.py