device: 0
seed: 2021
log_interval: 300

# DATA params
orig_dir: ../data/original_v3/
biom_dir: ../data/segmented/
spacy_dir: ../data/spacy/
pred_dir: ../predictions/
dev_miss: ../dev_miss.txt
output_folder: ../saved_models/
logs: ../logs/
## Log params
exp_name: 'n2c2'
model_name: 'bert'
# Hyper-parameters
batch_size: 32
epochs: 10
warmup_epochs: 0
## Markers params
max_tok_len: 300
max_pair_len: 10
ent_tok0: '[unused0]'
ent_tok1: '[unused1]'
## Bert params
dummy_data: False
hidden_dim: 768 
intermediate_dim: 2304 #3*768
# max_sent_len: 50
enc_dim: 768
enc_layers: 12
dropout: 0.3
lr: 0.00004
weight_decay: 0.000001
clip: 10
## Train params
patience: 5
accumulate_batches: 1
threshold: 0.5
event_weight: 0.5
# FLAGS
early_stop: True
# include_positions: True
freeze_pretrained: False
autoscalling: True

