# Experiment
description: bert-base-uncased rationale model on the negation task only
logdir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/context/bert_baselines/logs/
name: bert/negation_rationale
random_seed: 0

# Data
data_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v3/data_v3/
max_train_examples: null
sentences_dir: /home/jav/Documents/Projects/n2c2_2022/n2c2-track1/n2c2Track1TrainingData-v3/segmented/
tasks_to_load:
- Negation
window_size: 0

# Model
bert_model_name_or_path: bert-base-uncased
dropout_prob: 0.2
entity_pool_fn: first-last
freeze_pretrained: false
mark_entities: true
max_seq_length: 200
model_name: bert-rationale-classifier
use_entity_spans: true

# Losses
classifier_loss_fn: cross-entropy
classifier_loss_kwargs: {}
mask_loss_fn: controlled-sparsity
mask_loss_kwargs:
  selection_rate: 0.5
  transition_rate: 0.02

# Training
batch_size: 16
gradient_clip_val: 10.0
lr: 3.0e-05
max_epochs: 10
sample_strategy: null
weight_decay: 0.0

